#!/usr/bin/env bun
/**
 * Build script: generates manifest.ts with embedded content, then compiles to standalone binary.
 */
import { readdirSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
const SKILLS_DIR = join(ROOT, "skills");
const RULES_DIR = join(ROOT, "rules");
const HOOKS_DIR = join(ROOT, "hooks");
const SUBAGENTS_DIR = join(ROOT, "subagents");
const GENERATED_DIR = join(ROOT, "cli", "src", "generated");
const DIST_DIR = join(ROOT, "dist");

// ── Scan content directories ─────────────────────────────────

interface SkillData {
  files: Record<string, string>;
  subdirs: Record<string, Record<string, string>>;
}

function scanSkills(): Record<string, SkillData> {
  const result: Record<string, SkillData> = {};
  if (!dirExists(SKILLS_DIR)) return result;

  for (const entry of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const skillDir = join(SKILLS_DIR, entry.name);
    const skill: SkillData = { files: {}, subdirs: {} };

    for (const item of readdirSync(skillDir, { withFileTypes: true })) {
      if (item.isFile()) {
        skill.files[item.name] = readFileContent(join(skillDir, item.name));
      } else if (item.isDirectory()) {
        skill.subdirs[item.name] = {};
        const subDir = join(skillDir, item.name);
        for (const sub of readdirSync(subDir, { withFileTypes: true })) {
          if (sub.isFile()) {
            skill.subdirs[item.name][sub.name] = readFileContent(
              join(subDir, sub.name),
            );
          }
        }
      }
    }

    result[entry.name] = skill;
  }
  return result;
}

function scanFlatDir(dir: string, ext?: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!dirExists(dir)) return result;

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (ext && !entry.name.endsWith(ext)) continue;
    result[entry.name] = readFileContent(join(dir, entry.name));
  }
  return result;
}

function scanHooks(): Record<string, string> {
  const result: Record<string, string> = {};
  if (!dirExists(HOOKS_DIR)) return result;

  for (const entry of readdirSync(HOOKS_DIR, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith(".sh") && !entry.name.endsWith(".bash")) continue;
    result[entry.name] = readFileContent(join(HOOKS_DIR, entry.name));
  }
  return result;
}

// ── Generate manifest ────────────────────────────────────────

function buildManifestSource(
  skills: Record<string, SkillData>,
  rules: Record<string, string>,
  hooks: Record<string, string>,
  subagents: Record<string, string>,
): string {
  const lines: string[] = [
    "// Auto-generated by cli/scripts/build.ts — do not edit",
    "",
  ];

  // Skills
  lines.push(
    `export const SKILLS: Record<string, { files: Record<string, string>; subdirs: Record<string, Record<string, string>> }> = ${jsonToTemplate(skills)};`,
  );
  lines.push("");

  // Rules
  lines.push(
    `export const RULES: Record<string, string> = ${jsonToTemplate(rules)};`,
  );
  lines.push("");

  // Hooks
  lines.push(
    `export const HOOKS: Record<string, string> = ${jsonToTemplate(hooks)};`,
  );
  lines.push("");

  // Subagents
  lines.push(
    `export const SUBAGENTS: Record<string, string> = ${jsonToTemplate(subagents)};`,
  );
  lines.push("");

  return lines.join("\n");
}

/** Convert object to a string using template literals for values to preserve newlines cleanly */
function jsonToTemplate(obj: unknown): string {
  return JSON.stringify(obj, null, 2);
}

// ── Helpers ──────────────────────────────────────────────────

function dirExists(path: string): boolean {
  return existsSync(path);
}

function readFileContent(path: string): string {
  return readFileSync(path, "utf-8");
}

// ── Main ─────────────────────────────────────────────────────

async function main() {
  console.log("📦 Generating manifest...");

  mkdirSync(GENERATED_DIR, { recursive: true });

  const skills = scanSkills();
  const rules = scanFlatDir(RULES_DIR, ".md");
  const hooks = scanHooks();
  const subagents = scanFlatDir(SUBAGENTS_DIR, ".md");

  const manifestContent = buildManifestSource(skills, rules, hooks, subagents);
  const manifestPath = join(GENERATED_DIR, "manifest.ts");
  await Bun.write(manifestPath, manifestContent);

  console.log(
    `  ${Object.keys(skills).length} skills, ${Object.keys(rules).length} rules, ${Object.keys(hooks).length} hooks, ${Object.keys(subagents).length} subagents`,
  );

  console.log("🔨 Compiling binary...");
  mkdirSync(DIST_DIR, { recursive: true });

  const outfile = join(DIST_DIR, "af");
  const entrypoint = join(ROOT, "cli", "src", "install.ts");

  const result = Bun.spawnSync(
    [
      "bun",
      "build",
      "--compile",
      "--define",
      "__COMPILED__=true",
      "--outfile",
      outfile,
      entrypoint,
    ],
    {
      cwd: ROOT,
      stdout: "inherit",
      stderr: "inherit",
    },
  );

  if (result.exitCode !== 0) {
    console.error("❌ Compilation failed");
    process.exit(1);
  }

  console.log(`✅ Binary ready: ${outfile}`);
}

main();
