import { existsSync, mkdirSync, readFileSync, rmSync, renameSync } from "node:fs";
import { join } from "node:path";
import { config, HOME, dirExists } from "./config.ts";
import { parseFrontmatterFromString, buildRulesyncFrontmatter } from "./helpers.ts";
import { getSkillMeta } from "./skills.ts";
import { ensureRulesyncRuntime, getRulesyncBinPath } from "./rulesync-runtime.ts";
import {
  listSkillDirsAsync,
  materializeSkillToDir,
  listRuleFiles,
  readRuleContent,
} from "./assets.ts";

const TARGETS = ["claudecode", "codexcli", "factorydroid"];

export interface SyncOptions {
  features: ("skills" | "rules")[];
  global: boolean;
  targets?: string[];
  onStatus?: (message: string) => void;
  langs?: Set<string>;
  filter?: {
    skill?: string;
    skills?: string[];
    rule?: string;
    rules?: string[];
  };
  dryRun?: boolean;
}

export async function sync(opts: SyncOptions): Promise<void> {
  const skipExec = !!Bun.env.AF_SKIP_RULESYNC_EXEC;
  if (!skipExec) {
    await ensureRulesyncRuntime({ onStatus: opts.onStatus, silent: !opts.onStatus });
  }
  // When global, stage temp files in HOME so rulesync writes to ~/.claude/ etc.
  // rulesync v7 with global:true reads sources from ~/.rulesync/ instead of CWD,
  // so we avoid that by always using global:false and controlling output via CWD.
  const baseDir = opts.global ? HOME : process.cwd();

  // For HOME-based (user-scope) runs, pre-existing native rulesync state is
  // expected and must be preserved. We back up and restore instead of blocking.
  // For project-scope (CWD) runs, native configs still block to protect the project.
  let backedUp: BackedUpState | undefined;
  if (opts.global) {
    backedUp = backupExistingRulesync(baseDir);
  } else {
    guardExistingRulesync(baseDir);
  }

  try {
    if (skipExec) return;

    if (opts.features.includes("skills") && (opts.targets ?? TARGETS).includes("factorydroid")) {
      opts.onStatus?.(`Destino Droid skills: ${getFactorydroidSkillsDestination(opts.global)}`);
    }

    opts.onStatus?.("Preparando archivos temporales…");
    await prepareTemp(baseDir, opts);
    opts.onStatus?.("Sincronizando archivos…");
    runRulesync(baseDir, opts);
  } finally {
    cleanup(baseDir);
    if (backedUp) restoreRulesyncBackup(baseDir, backedUp);
  }
}

export function shouldEnableSimulateSkills(opts: SyncOptions): boolean {
  const targets = opts.targets ?? TARGETS;
  return opts.features.includes("skills") && targets.includes("factorydroid");
}

export function getFactorydroidSkillsDestination(global: boolean): string {
  return global ? "~/.factory/skills/*" : ".factory/skills/*";
}

/** Marker embedded in CLI-generated rulesync.jsonc to distinguish from native configs */
const AF_GENERATED_MARKER = "@af-generated";

/** Keys the CLI always writes in legacy (pre-marker) generated configs — no more, no less */
const LEGACY_CLI_KEYS = new Set(["$schema", "targets", "features", "global", "delete"]);

/** Known values for the "features" array in CLI-generated configs */
const KNOWN_FEATURES = new Set(["skills", "rules"]);

/** Known target values the CLI writes — any target outside this set means native config */
const KNOWN_CLI_TARGETS = new Set(["claudecode", "codexcli", "factorydroid"]);

/**
 * Detect whether a rulesync.jsonc content was generated by the CLI.
 *
 * Checks for the explicit marker first (new format). Falls back to a strict
 * structural heuristic for legacy residuals that requires the *exact* set of
 * keys the CLI used to write, valid feature values, and `global: false`.
 *
 * This avoids false positives on native configs that merely share the same
 * schema URL or happen to set `"delete": false`.
 */
function isAfGeneratedConfig(content: string): boolean {
  // Explicit marker (preferred, deterministic)
  if (content.includes(AF_GENERATED_MARKER)) return true;

  // Strict structural heuristic for legacy residuals (pre-marker CLI runs)
  // The CLI always wrote exactly { $schema, targets, features, global, delete }
  // with global===false and features containing only known values.
  try {
    // Strip single-line JS comments (// …) that may appear in .jsonc
    const jsonStr = content.replace(/^\s*\/\/.*$/gm, "").trim();
    if (!jsonStr) return false;

    const parsed = JSON.parse(jsonStr) as Record<string, unknown>;
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return false;

    const keys = new Set(Object.keys(parsed));

    // Must have exactly the CLI key set — extra keys mean native config
    if (keys.size !== LEGACY_CLI_KEYS.size) return false;
    for (const k of LEGACY_CLI_KEYS) {
      if (!keys.has(k)) return false;
    }

    // global must be exactly false (CLI always set global:false)
    if (parsed["global"] !== false) return false;

    // delete must be exactly false
    if (parsed["delete"] !== false) return false;

    // features must be an array of known CLI feature strings
    const features = parsed["features"];
    if (!Array.isArray(features) || features.length === 0) return false;
    for (const f of features) {
      if (typeof f !== "string" || !KNOWN_FEATURES.has(f)) return false;
    }

    // targets must be a non-empty array containing only known CLI target values
    const targets = parsed["targets"];
    if (!Array.isArray(targets) || targets.length === 0) return false;
    for (const t of targets) {
      if (typeof t !== "string" || !KNOWN_CLI_TARGETS.has(t)) return false;
    }

    // Schema must reference the known rulesync schema
    if (typeof parsed["$schema"] !== "string" || !parsed["$schema"].includes("dyoshikawa/rulesync"))
      return false;

    // Extra safety: only treat as residual if not tracked by git
    const gitCheck = Bun.spawnSync(["git", "ls-files", "rulesync.jsonc"], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const tracked = gitCheck.exitCode === 0 && gitCheck.stdout.toString().trim().length > 0;
    if (tracked) return false;

    return true;
  } catch {
    // JSON parse failure → not a CLI-generated config
    return false;
  }
}

/**
 * Guard against overwriting a project that genuinely uses rulesync natively.
 *
 * If residual files from a previous CLI run are detected (identified by the
 * AF_GENERATED_MARKER), they are cleaned up automatically so the current
 * run can proceed. Only truly native (non-CLI-generated) rulesync configs
 * trigger a hard block.
 */
function guardExistingRulesync(cwd: string): void {
  const rulesyncDir = join(cwd, ".rulesync");
  const configFile = join(cwd, "rulesync.jsonc");

  const hasDir = dirExists(rulesyncDir);
  const hasConfig = existsSync(configFile);

  if (!hasDir && !hasConfig) return;

  // Check if rulesync.jsonc is a CLI-generated residual
  if (hasConfig) {
    try {
      const content = readFileSync(configFile, "utf-8");
      if (isAfGeneratedConfig(content)) {
        // Residual from a previous CLI run — clean up and proceed
        console.log("⚠️  Cleaning up residual rulesync artifacts from a previous run…");
        cleanup(cwd);
        return;
      }
    } catch {
      // If we can't read the file, fall through to the native guard
    }
  }

  // If only .rulesync/ dir exists without a config file, it may be a residual staging dir
  if (hasDir && !hasConfig) {
    const markerFile = join(rulesyncDir, ".af-staging");
    if (dirExists(markerFile)) {
      console.log("⚠️  Cleaning up residual rulesync staging from a previous run…");
      cleanup(cwd);
      return;
    }
  }

  // Non-CLI rulesync detected — block to protect native configuration
  console.log("❌ Native rulesync configuration detected (.rulesync/ or rulesync.jsonc exists).");
  console.log(
    "   This project appears to manage rulesync independently. Remove the native config to use af.",
  );
  process.exit(1);
}

async function prepareTemp(cwd: string, opts: SyncOptions): Promise<void> {
  const targets = opts.targets ?? TARGETS;

  // Create .rulesync staging dir with a marker so the guard can identify CLI-generated residuals
  const stagingDir = join(cwd, ".rulesync");
  mkdirSync(stagingDir, { recursive: true });
  await Bun.write(join(stagingDir, ".af-staging"), "");

  if (opts.features.includes("skills")) {
    await prepareSkills(cwd, opts, targets);
  }
  if (opts.features.includes("rules")) {
    await prepareRules(cwd, opts, targets);
  }

  const rulesyncConfig = {
    $schema:
      "https://raw.githubusercontent.com/dyoshikawa/rulesync/refs/heads/main/config-schema.json",
    targets,
    features: opts.features,
    global: false,
    delete: false,
  };
  const configJson = JSON.stringify(rulesyncConfig, null, 2);
  await Bun.write(
    join(cwd, "rulesync.jsonc"),
    `// ${AF_GENERATED_MARKER} — do not edit; will be cleaned up automatically\n${configJson}`,
  );
}

async function prepareSkills(cwd: string, opts: SyncOptions, targets: string[]): Promise<void> {
  const skills = await listSkillDirsAsync();

  for (const skillName of skills) {
    const meta = await getSkillMeta(skillName);
    if (!meta) continue;

    // Filter by lang if applicable
    if (opts.langs && meta.langs.length > 0) {
      const hasMatch = meta.langs.some((l) => opts.langs!.has(l));
      if (!hasMatch) continue;
    }

    // Filter by name if installing a single skill
    if (opts.filter?.skill && skillName !== opts.filter.skill) continue;
    if (opts.filter?.skills && !opts.filter.skills.includes(skillName)) continue;

    const destDir = join(cwd, ".rulesync", "skills", skillName);
    await materializeSkillToDir(skillName, destDir);

    // Rewrite SKILL.md frontmatter: add targets
    const skillMdPath = join(destDir, "SKILL.md");
    const raw = await Bun.file(skillMdPath).text();
    const rewritten = addTargetsToFrontmatter(raw, targets);
    await Bun.write(skillMdPath, rewritten);
  }
}

function addTargetsToFrontmatter(raw: string, targets: string[]): string {
  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) {
    // No frontmatter — wrap entire content
    const targetLines = targets.map((t) => `  - ${t}`).join("\n");
    return `---\ntargets:\n${targetLines}\n---\n${raw}`;
  }

  const yaml = fmMatch[1];
  const body = fmMatch[2];
  const targetLines = targets.map((t) => `  - ${t}`).join("\n");
  return `---\n${yaml}\ntargets:\n${targetLines}\n---\n${body}`;
}

async function prepareRules(cwd: string, opts: SyncOptions, targets: string[]): Promise<void> {
  const ruleFiles = await listRuleFiles();
  if (ruleFiles.length === 0) return;

  const tempRulesDir = join(cwd, ".rulesync", "rules");
  mkdirSync(tempRulesDir, { recursive: true });

  for (const fileName of ruleFiles) {
    const ruleName = fileName.replace(/\.md$/, "");

    // Filter by name if installing a single rule
    if (opts.filter?.rule && ruleName !== opts.filter.rule) continue;
    if (opts.filter?.rules && !opts.filter.rules.includes(ruleName)) continue;

    // Skip language-specific rules if language not detected (unless global/user-level with no filter)
    if (opts.langs && !opts.global) {
      if (ruleName === "typescript" && !opts.langs.has("typescript")) continue;
      if (ruleName === "python" && !opts.langs.has("python")) continue;
    }

    const raw = await readRuleContent(fileName);
    if (!raw) continue;

    const { data, content } = parseFrontmatterFromString(raw);

    const description = (data.description as string) || ruleName + " conventions";

    // Convert paths -> globs
    let globs: string[] | undefined;
    if (Array.isArray(data.paths)) {
      globs = data.paths as string[];
    } else if (Array.isArray(data.globs)) {
      globs = data.globs as string[];
    }

    const root = !globs;

    const frontmatter = buildRulesyncFrontmatter({
      description,
      root,
      globs,
      targets,
    });

    await Bun.write(join(tempRulesDir, fileName), frontmatter + "\n" + content);
  }
}

function runRulesync(cwd: string, opts: SyncOptions): void {
  const args = [getRulesyncBinPath(), "generate"];

  // rulesync 7.12.x currently gates project-scope factorydroid skills behind
  // --simulate-skills despite documenting native support.
  if (shouldEnableSimulateSkills(opts)) {
    args.push("--simulate-skills");
  }

  if (opts.dryRun ?? config.dryRun) {
    args.push("--dry-run");
  }

  const result = Bun.spawnSync(args, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
  });

  if (result.exitCode !== 0) {
    console.log("❌ rulesync generate failed");
    process.exit(1);
  }
}

function cleanup(cwd: string): void {
  const rulesyncDir = join(cwd, ".rulesync");
  const configFile = join(cwd, "rulesync.jsonc");

  if (dirExists(rulesyncDir)) {
    rmSync(rulesyncDir, { recursive: true, force: true });
  }
  if (existsSync(configFile)) {
    rmSync(configFile, { force: true });
  }
}

// ── Backup/restore for HOME-based (user-scope) runs ──────────
//
// When running in HOME, pre-existing native rulesync state (.rulesync/ and
// rulesync.jsonc) is expected and must survive the CLI's staging cycle.
// We move them to a temp location before staging and restore after cleanup.

interface BackedUpState {
  hadDir: boolean;
  hadConfig: boolean;
  backupDir: string;
}

/**
 * Back up pre-existing .rulesync/ and rulesync.jsonc in cwd before staging.
 * Also handles CLI-generated residuals: if detected, cleans them instead of backing up.
 */
function backupExistingRulesync(cwd: string): BackedUpState | undefined {
  const rulesyncDir = join(cwd, ".rulesync");
  const configFile = join(cwd, "rulesync.jsonc");

  const hasDir = dirExists(rulesyncDir);
  const hasConfig = existsSync(configFile);

  if (!hasDir && !hasConfig) return undefined;

  // Check if the config is a CLI-generated residual (from a crashed/interrupted run)
  if (hasConfig) {
    try {
      const content = readFileSync(configFile, "utf-8");
      if (isAfGeneratedConfig(content)) {
        // Residual from a previous CLI run — clean up and proceed (no backup needed)
        console.log("⚠️  Cleaning up residual rulesync artifacts from a previous run…");
        cleanup(cwd);
        return undefined;
      }
    } catch {
      // Cannot read — fall through to backup
    }
  }

  // Check if .rulesync/ dir is a CLI staging residual
  if (hasDir && !hasConfig) {
    const markerFile = join(rulesyncDir, ".af-staging");
    if (dirExists(markerFile)) {
      console.log("⚠️  Cleaning up residual rulesync staging from a previous run…");
      cleanup(cwd);
      return undefined;
    }
  }

  // Pre-existing native state — back it up
  const backupDir = join(cwd, ".rulesync-af-backup-" + Date.now());
  mkdirSync(backupDir, { recursive: true });

  if (hasDir) {
    renameSync(rulesyncDir, join(backupDir, ".rulesync"));
  }
  if (hasConfig) {
    renameSync(configFile, join(backupDir, "rulesync.jsonc"));
  }

  return { hadDir: hasDir, hadConfig: hasConfig, backupDir };
}

/**
 * Restore previously backed-up native rulesync state after cleanup.
 */
function restoreRulesyncBackup(cwd: string, state: BackedUpState): void {
  try {
    if (state.hadDir) {
      const backedUpDir = join(state.backupDir, ".rulesync");
      if (dirExists(backedUpDir)) {
        renameSync(backedUpDir, join(cwd, ".rulesync"));
      }
    }
    if (state.hadConfig) {
      const backedUpConfig = join(state.backupDir, "rulesync.jsonc");
      if (existsSync(backedUpConfig)) {
        renameSync(backedUpConfig, join(cwd, "rulesync.jsonc"));
      }
    }
  } finally {
    // Always clean up the backup directory
    if (dirExists(state.backupDir)) {
      rmSync(state.backupDir, { recursive: true, force: true });
    }
  }
}
