import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { config, HOME, dirExists } from "./config.ts";
import { parseFrontmatterFromString, buildRulesyncFrontmatter } from "./helpers.ts";
import { getSkillMeta } from "./skills.ts";
import {
  listSkillDirsAsync,
  materializeSkillToDir,
  listRuleFiles,
  readRuleContent,
} from "./assets.ts";

const TARGETS = ["claudecode", "codexcli", "factorydroid"];

export interface SyncOptions {
  features: ("skills" | "rules")[];
  global: boolean;
  targets?: string[];
  langs?: Set<string>;
  filter?: {
    skill?: string;
    skills?: string[];
    rule?: string;
    rules?: string[];
  };
  dryRun?: boolean;
}

export async function sync(opts: SyncOptions): Promise<void> {
  ensureRulesync();
  // When global, stage temp files in HOME so rulesync writes to ~/.claude/ etc.
  // rulesync v7 with global:true reads sources from ~/.rulesync/ instead of CWD,
  // so we avoid that by always using global:false and controlling output via CWD.
  const baseDir = opts.global ? HOME : process.cwd();
  guardExistingRulesync(baseDir);

  try {
    await prepareTemp(baseDir, opts);
    runRulesync(baseDir, opts);
  } finally {
    cleanup(baseDir);
  }
}

function ensureRulesync(): void {
  const result = Bun.spawnSync(["npx", "rulesync", "--version"]);
  if (result.exitCode !== 0) {
    console.log("❌ rulesync not found via npx");
    process.exit(1);
  }
}

/** Marker embedded in CLI-generated rulesync.jsonc to distinguish from native configs */
const AF_GENERATED_MARKER = "@af-generated";

/**
 * Detect whether a rulesync.jsonc content was generated by the CLI.
 *
 * Checks for the explicit marker first (new format). Falls back to a
 * structural heuristic for legacy residuals: the file must contain the
 * rulesync schema URL **and** the "delete": false field the CLI always sets,
 * and must NOT be tracked by git.
 */
function isAfGeneratedConfig(content: string): boolean {
  // Explicit marker (preferred, deterministic)
  if (content.includes(AF_GENERATED_MARKER)) return true;

  // Structural heuristic for legacy residuals (pre-marker CLI runs)
  const hasSchema = content.includes("dyoshikawa/rulesync");
  const hasDeleteFalse = content.includes('"delete": false') || content.includes('"delete":false');
  if (hasSchema && hasDeleteFalse) {
    // Extra safety: only treat as residual if not tracked by git
    const gitCheck = Bun.spawnSync(["git", "ls-files", "rulesync.jsonc"], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const tracked = gitCheck.exitCode === 0 && gitCheck.stdout.toString().trim().length > 0;
    if (!tracked) return true;
  }

  return false;
}

/**
 * Guard against overwriting a project that genuinely uses rulesync natively.
 *
 * If residual files from a previous CLI run are detected (identified by the
 * AF_GENERATED_MARKER), they are cleaned up automatically so the current
 * run can proceed. Only truly native (non-CLI-generated) rulesync configs
 * trigger a hard block.
 */
function guardExistingRulesync(cwd: string): void {
  const rulesyncDir = join(cwd, ".rulesync");
  const configFile = join(cwd, "rulesync.jsonc");

  const hasDir = dirExists(rulesyncDir);
  const hasConfig = existsSync(configFile);

  if (!hasDir && !hasConfig) return;

  // Check if rulesync.jsonc is a CLI-generated residual
  if (hasConfig) {
    try {
      const content = readFileSync(configFile, "utf-8");
      if (isAfGeneratedConfig(content)) {
        // Residual from a previous CLI run — clean up and proceed
        console.log("⚠️  Cleaning up residual rulesync artifacts from a previous run…");
        cleanup(cwd);
        return;
      }
    } catch {
      // If we can't read the file, fall through to the native guard
    }
  }

  // If only .rulesync/ dir exists without a config file, it may be a residual staging dir
  if (hasDir && !hasConfig) {
    const markerFile = join(rulesyncDir, ".af-staging");
    if (dirExists(markerFile)) {
      console.log("⚠️  Cleaning up residual rulesync staging from a previous run…");
      cleanup(cwd);
      return;
    }
  }

  // Non-CLI rulesync detected — block to protect native configuration
  console.log("❌ Native rulesync configuration detected (.rulesync/ or rulesync.jsonc exists).");
  console.log(
    "   This project appears to manage rulesync independently. Remove the native config to use af.",
  );
  process.exit(1);
}

async function prepareTemp(cwd: string, opts: SyncOptions): Promise<void> {
  const targets = opts.targets ?? TARGETS;

  // Create .rulesync staging dir with a marker so the guard can identify CLI-generated residuals
  const stagingDir = join(cwd, ".rulesync");
  mkdirSync(stagingDir, { recursive: true });
  await Bun.write(join(stagingDir, ".af-staging"), "");

  if (opts.features.includes("skills")) {
    await prepareSkills(cwd, opts, targets);
  }
  if (opts.features.includes("rules")) {
    await prepareRules(cwd, opts, targets);
  }

  const rulesyncConfig = {
    $schema:
      "https://raw.githubusercontent.com/dyoshikawa/rulesync/refs/heads/main/config-schema.json",
    targets,
    features: opts.features,
    global: false,
    delete: false,
  };
  const configJson = JSON.stringify(rulesyncConfig, null, 2);
  await Bun.write(
    join(cwd, "rulesync.jsonc"),
    `// ${AF_GENERATED_MARKER} — do not edit; will be cleaned up automatically\n${configJson}`,
  );
}

async function prepareSkills(cwd: string, opts: SyncOptions, targets: string[]): Promise<void> {
  const skills = await listSkillDirsAsync();

  for (const skillName of skills) {
    const meta = await getSkillMeta(skillName);
    if (!meta) continue;

    // Filter by scope
    if (opts.global && meta.scope !== "global") continue;
    if (!opts.global && meta.scope !== "project") continue;

    // Filter by lang if applicable
    if (opts.langs && meta.langs.length > 0) {
      const hasMatch = meta.langs.some((l) => opts.langs!.has(l));
      if (!hasMatch) continue;
    }

    // Filter by name if installing a single skill
    if (opts.filter?.skill && skillName !== opts.filter.skill) continue;
    if (opts.filter?.skills && !opts.filter.skills.includes(skillName)) continue;

    const destDir = join(cwd, ".rulesync", "skills", skillName);
    await materializeSkillToDir(skillName, destDir);

    // Rewrite SKILL.md frontmatter: add targets
    const skillMdPath = join(destDir, "SKILL.md");
    const raw = await Bun.file(skillMdPath).text();
    const rewritten = addTargetsToFrontmatter(raw, targets);
    await Bun.write(skillMdPath, rewritten);
  }
}

function addTargetsToFrontmatter(raw: string, targets: string[]): string {
  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) {
    // No frontmatter — wrap entire content
    const targetLines = targets.map((t) => `  - ${t}`).join("\n");
    return `---\ntargets:\n${targetLines}\n---\n${raw}`;
  }

  const yaml = fmMatch[1];
  const body = fmMatch[2];
  const targetLines = targets.map((t) => `  - ${t}`).join("\n");
  return `---\n${yaml}\ntargets:\n${targetLines}\n---\n${body}`;
}

async function prepareRules(cwd: string, opts: SyncOptions, targets: string[]): Promise<void> {
  const ruleFiles = await listRuleFiles();
  if (ruleFiles.length === 0) return;

  const tempRulesDir = join(cwd, ".rulesync", "rules");
  mkdirSync(tempRulesDir, { recursive: true });

  for (const fileName of ruleFiles) {
    const ruleName = fileName.replace(/\.md$/, "");

    // Filter by name if installing a single rule
    if (opts.filter?.rule && ruleName !== opts.filter.rule) continue;
    if (opts.filter?.rules && !opts.filter.rules.includes(ruleName)) continue;

    // Skip language-specific rules if language not detected (unless global/user-level with no filter)
    if (opts.langs && !opts.global) {
      if (ruleName === "typescript" && !opts.langs.has("typescript")) continue;
      if (ruleName === "python" && !opts.langs.has("python")) continue;
    }

    const raw = await readRuleContent(fileName);
    if (!raw) continue;

    const { data, content } = parseFrontmatterFromString(raw);

    const description = (data.description as string) || ruleName + " conventions";

    // Convert paths -> globs
    let globs: string[] | undefined;
    if (Array.isArray(data.paths)) {
      globs = data.paths as string[];
    } else if (Array.isArray(data.globs)) {
      globs = data.globs as string[];
    }

    const root = !globs;

    const frontmatter = buildRulesyncFrontmatter({
      description,
      root,
      globs,
      targets,
    });

    await Bun.write(join(tempRulesDir, fileName), frontmatter + "\n" + content);
  }
}

function runRulesync(cwd: string, opts: SyncOptions): void {
  const args = ["npx", "rulesync", "generate"];

  if (opts.dryRun ?? config.dryRun) {
    args.push("--dry-run");
  }

  const result = Bun.spawnSync(args, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
  });

  if (result.exitCode !== 0) {
    console.log("❌ rulesync generate failed");
    process.exit(1);
  }
}

function cleanup(cwd: string): void {
  const rulesyncDir = join(cwd, ".rulesync");
  const configFile = join(cwd, "rulesync.jsonc");

  if (dirExists(rulesyncDir)) {
    rmSync(rulesyncDir, { recursive: true, force: true });
  }
  if (existsSync(configFile)) {
    rmSync(configFile, { force: true });
  }
}
